### ISSUE TITLE
connect_to_emu_without_snr will cause a SEGGER pop-up window

### ISSUE THREAD

**Issue by mjdietzx** [martinhath/rtt-logger#2]
https://github.com/martinhath/rtt-logger/blob/master/src/rtt-logger.py#L83

I would recommend something like:

devices = nrf.enum_emu_snr()
if (devices == []):
  return []
else:
  #...

**Comment by martinhath** [comment]
I didn't experience this issue, as there is no SEGGER window on my machine :stuck_out_tongue:
